### ISSUE TITLE
See full policy text for one policy

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#527]
As an agency implementer, I want to be able to see both the full policy text as well as be able to quickly see (and even filter) all the things in that policy that are required of my agency.

## ac 
- [x] user can read full policy text for _one policy_ within the policy library
- [x] user can see policy metadata including – policy title, policy document number (e.g. M-09-17), issue date, and issuing agency
- [x] Including headings!, fonts, color pallette 

## notes 
- future iterations of this page will include requirement highlighting (and possibly other type of content highlighting), within-document navigation, definitions of terms, etc. 
- Ideally this story can be completed and deployed within the live site – however if that's not possible an interactive prototype can also work.

**Comment by carodew** [comment]
Note – in lieu of any other suggested policy docs, we can use M-10-06: Memorandum for the Heads of Executive Departments and Agencies, since we already have some sketches using this content that @nicoleslaw had done previously.

**Comment by carodew** [comment]
Bill recommends using M-16-19 or M-13-13 as the document to design around. 

Here are other options to play around with variables – 

* A document that is very short with few requirements:
*       M-16-14: Category Management Policy 16-2: Providing Comprehensive Identity Protection Services, Identity Monitoring, and Data Breach Response (3 pages, 10 requirements)
* A document that is very long with many requirements:
*       Circular A-130 (85 pages, 444 requirements)
* A document of average length with some requirements, preferably one we've already entered into the system or is very popular (e.g. M-16-19, M-13-13, etc).
*       M-16-19: Data Center Optimization Initiative (DCOI) (11 pages, 66 requirements)
*       M-13-13: Open Data Policy-Managing Information as an Asset (12 pages, 23 requirements)

**Comment by carodew** [comment]
List of content types in M-16-19

- title + header information
- h1 through h2
- regular ole text
- tables
- footnotes
- URLs 
- bulleted lists (uls) 
- numbered lists (ols) 
- acronyms (e.g. FITARA)

**Comment by cmc333333** [comment]
Just wanted to drop a reminder about the current fields we have in case it helps your design. Certainly not clear which are relevant to user needs.

## Policy Metadata
* id (our integer primary key)
* policy_number (an integer key that OMB developed. this isn't something users will recognize)
* title (these usually don't include the short name, like "M-16-19")
* uri (to a pdf/otherwise version)
* omb_policy_id (this is the short name, like "M-16-19"). Can be blank.
* policy_type (one of Circular, Executive Order, Guidance, HSPD, Law, Memorandum, National Action Plan, Plan, PPD, Policy Review, Standards, Strategy). Can be blank.
* issuance (Date)
* sunset (Date). Can be blank.
* policy status (Text field). Can be blank
* issuing body (Text field)

## Requirement Metadata
Many of these are fields we carried over from the original CSV, so we aren't positive of their purpose. Poke at [their csv](https://github.com/ombegov/policy-v2/blob/master/assets/AllPhasesCombinedTaggingTemp_March28_for18f.csv) to see sample content.
* id (our integer primary key)
* req_id (a numbering scheme OMB came up with of the form "{policy number}.{unique id}". Means nothing outside of this project)
* policy_section (Text field describing the header under which this requirement appears). Can be blank
* policy_sub_section (Same for a sub-header). Can be blank.
* verb (Text field). Can be blank.
* impacted entity (Text field -- agency names and organizations). Can be blank.
* req_deadline (Text field). Can be blank.
* citation (Text field). Can be blank.
* req_status (Text field). Can be blank.
* precedent (Text field). Can be blank.
* related_reqs (Text field). Can be blank.
* omb_data_collection (Text field). Can be blank.
* topics (Multiselect). Can be blank
* agencies and agency groups (Multiselects). Can be blank. Aren't well populated.

**Comment by cmc333333** [comment]
Also, I wonder how many of the eRegs content types will be relevant. Off the top of my head, we saw:

## Types of paragraphs
* numbered/lettered paragraphs (with lots of nesting)
* unnumbered paragraphs
* bulleted lists
* tables
* images
* "Notes" which commented on the text but was also part of the document
* mathematical equations
* chunks of pre-formatted computer code
* extracts from other documents, embedded inside this one
* sets of paragraphs which were intended to be copy-pasted from ("posters")

## Inlines
* defining a term
* using a defined term
* internal-to-the-document citations
* external-to-the-document citations
* footnotes
* subscripts/superscripts

We also embedded or linked to documents which provided further analysis of specific paragraphs. Some of these came from prior to the document (e.g. text explaining why particular paragraphs were added) and some came after (e.g. clarifications, practical implementation details, etc.)

**Comment by carodew** [comment]
Just to summarize previous conversations here – we've decided that the only potentially interactive content we need at the outset is footnotes, since those are part of the original policy text. 

We talked a little bit about tables and math yesterday too and I'm not sure if they go here or a separate story (although I'd probably vote for separate). 

Does that sound accurate @yowill ?

**Comment by yowill** [comment]
Correct @carodew, those should be separate stories / dragons. :)

**Comment by carodew** [comment]
Regarding footnotes, we want to be sure we don't dump screen reader and keyboard users at the end of a page without providing them a way to easily get back to where they left off in the text. 

![screenreader - footnotes](https://user-images.githubusercontent.com/10144074/31823204-4c1490a6-b579-11e7-8ad7-bc0d0eb0175d.png)

**Comment by carodew** [comment]
I've broken out the 'layered ons' into – 

- #566 - footnotes
- #565 - math
- #564 - tables

**Comment by rtwell** [comment]
#### hey gang! here be me first pass ☠️ 

I assume all of this will change or be tweaked, but it's a great start! If anyone sees something we need to add or if you need any specificity, don't hesitate to ask! 

[sketch file here](https://github.com/18F/omb-eregs/files/1423318/VisualDesign0.3.6-WIP.zip) for those that want it

### text and color
![omb styles](https://user-images.githubusercontent.com/12564977/32123106-9b57b80a-bb28-11e7-85cf-0ffa45626dad.png)

### mobile typography
![omb mobile type](https://user-images.githubusercontent.com/12564977/32123202-f65e5a10-bb28-11e7-86fa-9c0ec63ba39d.png)

### main policy page, with a table
![full policy page](https://user-images.githubusercontent.com/12564977/32123210-fc7e6192-bb28-11e7-956f-abf8279fba0e.png)

### footnote in opened state (hover at the top of the page)
![footnote](https://user-images.githubusercontent.com/12564977/32123230-05e44a26-bb29-11e7-8b1f-370f4288729d.png)

**Comment by cmc333333** [comment]
Designs complete and key implementation issues have been broken into multiple issues, so closing.
