### ISSUE TITLE
As a Policy Analyst, I want to edit preamble information that the importer identified, and enter preamble information that's missing.

### ISSUE THREAD

**Issue by austinhernandez** [18F/omb-eregs#831]
## Epic
As a Policy Analyst, I want to enter preamble information (issued by, from, etc.) so that it is correctly displayed on the [Policy Library page](https://omb-eregs-demo.app.cloud.gov/document/M-16-19).
  
## Acceptance criteria
- [ ] All form fields and labels match with the frond-end UI display
- [ ] Functionality and space allowing for complex data if needed (XML, tables, math, etc.) 

## Outstanding questions
- [ ] Different types of documents have different kinds of information within the preamble. What are the most common kinds of information that we need to account for? 

## Definition of done
- [ ] Space for Preamble information included in the policy editor interface
- [ ] Design styling matches the rest of the document
- [ ] Design style that flags or differentiates what the preamble is vs official policy (could just be a clear header design

## Stories
- As a Policy Analyst, I want to be able to add custom preamble data to documents so that I can give context, instruction, and more information outside of the policy documentation to agencies.
- As a public user, I want to visually be able to know what is the defined legal  policy and what is the preamble.

**Comment by carodew** [comment]
Note (from @rtwell 's brain) – there's a difference between 'optional' and "it's necessary if the document has it." (regarding preamble form fields)

**Comment by carodew** [comment]
On slightly further investigation, the preambles for Memos are pretty standard, and are so going back a long time. I think we can shelve this one until we more explicitly expand to other document types.
